export type UsState = {
  slug: string;
  name: string;
  abbr: string;
  dds: string;
  note: string;
};

export const US_STATES: UsState[] = [
  { slug: "alabama", name: "Alabama", abbr: "AL", dds: "Alabama Disability Determination Service", note: "Initial medical decisions are made by Alabama DDS under SSA rules. SSDI is a federal program — the same work-credit and medical standards apply in every state." },
  { slug: "alaska", name: "Alaska", abbr: "AK", dds: "Alaska Disability Determination Services", note: "Alaska DDS reviews medical evidence for SSA. Remote communities can file online at SSA.gov or by phone; we help gather records from tribal, VA, and private providers." },
  { slug: "arizona", name: "Arizona", abbr: "AZ", dds: "Arizona Disability Determination Services", note: "Arizona DDS applies federal SSDI rules. Heat-related, musculoskeletal, and respiratory claims are common; medical proof still must meet SSA duration and severity standards." },
  { slug: "arkansas", name: "Arkansas", abbr: "AR", dds: "Arkansas Disability Determination for Social Security Administration", note: "Arkansas DDS adjudicates initial and reconsideration claims. SSA field offices and SSA.gov remain the official filing channels." },
  { slug: "california", name: "California", abbr: "CA", dds: "California Department of Social Services — Disability Determination Services Division", note: "California has the largest DDS operation in the U.S. CCPA/CPRA privacy rights apply to California residents who submit this form. SSDI medical rules are still federal." },
  { slug: "colorado", name: "Colorado", abbr: "CO", dds: "Colorado Disability Determination Services", note: "Colorado DDS reviews claims under federal listings. The Colorado Privacy Act gives residents opt-out and sensitive-data rights for information collected on this site." },
  { slug: "connecticut", name: "Connecticut", abbr: "CT", dds: "Connecticut Disability Determination Services", note: "Connecticut DDS applies SSA’s five-step sequential evaluation. CTDPA consumer rights apply to personal data we collect from Connecticut residents." },
  { slug: "delaware", name: "Delaware", abbr: "DE", dds: "Delaware Disability Determination Services", note: "Delaware DDS makes the medical decision; SSA pays the benefit. Delaware’s Personal Data Privacy Act covers consumer rights for residents." },
  { slug: "florida", name: "Florida", abbr: "FL", dds: "Florida Division of Disability Determinations", note: "Florida’s Division of Disability Determinations processes SSDI medical reviews. High volume means complete medical records and work history matter. Florida’s Digital Bill of Rights and state telemarketing rules also apply." },
  { slug: "georgia", name: "Georgia", abbr: "GA", dds: "Georgia Disability Adjudication Services", note: "Georgia Disability Adjudication Services reviews medical evidence for SSA. File at SSA.gov or a local field office; we help organize applications and appeals." },
  { slug: "hawaii", name: "Hawaii", abbr: "HI", dds: "Hawaii Disability Determination Branch", note: "Hawaii DDS reviews claims under federal rules. Island residents can file online; we help coordinate records across Neighbor Island and military providers." },
  { slug: "idaho", name: "Idaho", abbr: "ID", dds: "Idaho Disability Determination Services", note: "Idaho DDS applies the same SSA listings used nationwide. Rural claimants often need extra help obtaining treating-source records." },
  { slug: "illinois", name: "Illinois", abbr: "IL", dds: "Illinois Bureau of Disability Determination Services", note: "Illinois BDS reviews SSDI claims. Illinois BIPA and two-party call-recording consent may apply to how we handle biometric data and recorded calls." },
  { slug: "indiana", name: "Indiana", abbr: "IN", dds: "Indiana Disability Determination Bureau", note: "Indiana’s Disability Determination Bureau applies federal SSDI criteria. Indiana’s Consumer Data Protection Act took effect in 2026." },
  { slug: "iowa", name: "Iowa", abbr: "IA", dds: "Iowa Disability Determination Services", note: "Iowa DDS adjudicates medical eligibility. Iowa’s Consumer Data Protection Act gives residents access, deletion, and opt-out rights." },
  { slug: "kansas", name: "Kansas", abbr: "KS", dds: "Kansas Disability Determination Services", note: "Kansas DDS uses SSA’s sequential evaluation. SSDI benefit amounts are based on your federal earnings record, not Kansas wages alone." },
  { slug: "kentucky", name: "Kentucky", abbr: "KY", dds: "Kentucky Disability Determination Services", note: "Kentucky DDS reviews claims for SSA. Kentucky’s Consumer Data Protection Act became effective in 2026." },
  { slug: "louisiana", name: "Louisiana", abbr: "LA", dds: "Louisiana Disability Determination Services", note: "Louisiana DDS applies federal medical listings. Louisiana’s Data Privacy Act is enacted and scheduled to take effect in 2027." },
  { slug: "maine", name: "Maine", abbr: "ME", dds: "Maine Disability Determination Services", note: "Maine DDS reviews SSDI medical evidence. You can file online, by phone, or at a Maine SSA field office at no charge." },
  { slug: "maryland", name: "Maryland", abbr: "MD", dds: "Maryland Disability Determination Services", note: "Maryland DDS adjudicates claims under federal rules. Maryland’s Online Data Privacy Act provides strong data-minimization and consumer rights." },
  { slug: "massachusetts", name: "Massachusetts", abbr: "MA", dds: "Massachusetts Disability Determination Services", note: "Massachusetts DDS reviews medical eligibility. Massachusetts is an all-party call-recording state — we provide notice before recording." },
  { slug: "michigan", name: "Michigan", abbr: "MI", dds: "Michigan Disability Determination Service", note: "Michigan DDS applies SSA listings. SSDI is federal insurance you paid for through FICA — it is not a Michigan welfare program." },
  { slug: "minnesota", name: "Minnesota", abbr: "MN", dds: "Minnesota Disability Determination Services", note: "Minnesota DDS reviews claims. Minnesota’s Consumer Data Privacy Act includes profiling and automated-decision explanation rights." },
  { slug: "mississippi", name: "Mississippi", abbr: "MS", dds: "Mississippi Disability Determination Services", note: "Mississippi DDS makes the medical determination for SSA. Complete treatment records from Mississippi providers speed review." },
  { slug: "missouri", name: "Missouri", abbr: "MO", dds: "Missouri Disability Determinations", note: "Missouri Disability Determinations applies the five-step process. SSA, not the State of Missouri, issues monthly SSDI payments." },
  { slug: "montana", name: "Montana", abbr: "MT", dds: "Montana Disability Determination Services", note: "Montana DDS reviews claims under federal rules. Montana’s Consumer Data Privacy Act has a lower consumer threshold than most states." },
  { slug: "nebraska", name: "Nebraska", abbr: "NE", dds: "Nebraska Disability Determination Services", note: "Nebraska DDS adjudicates SSDI medical decisions. Nebraska’s Data Privacy Act has no revenue threshold for covered businesses." },
  { slug: "nevada", name: "Nevada", abbr: "NV", dds: "Nevada Disability Determination Services", note: "Nevada DDS uses SSA criteria. Nevada has an opt-out-of-sale privacy statute even without a comprehensive consumer privacy code." },
  { slug: "new-hampshire", name: "New Hampshire", abbr: "NH", dds: "New Hampshire Disability Determination Unit", note: "New Hampshire’s DDU reviews medical evidence. New Hampshire’s Privacy Act covers residents’ access, correction, and opt-out rights." },
  { slug: "new-jersey", name: "New Jersey", abbr: "NJ", dds: "New Jersey Division of Disability Services — Disability Determination Services", note: "New Jersey DDS applies federal SSDI rules. The New Jersey Data Privacy Act took effect in 2025." },
  { slug: "new-mexico", name: "New Mexico", abbr: "NM", dds: "New Mexico Disability Determination Services", note: "New Mexico DDS reviews claims for SSA. Tribal, IHS, VA, and private records can all support a federal disability claim." },
  { slug: "new-york", name: "New York", abbr: "NY", dds: "New York State Office of Temporary and Disability Assistance — Division of Disability Determinations", note: "New York DDD processes a high volume of SSDI claims. SHIELD Act data-security duties and NY telemarketing rules apply to this site’s operations." },
  { slug: "north-carolina", name: "North Carolina", abbr: "NC", dds: "North Carolina Disability Determination Services", note: "North Carolina DDS applies SSA’s listings. You may file at SSA.gov even if you live in a rural NC county without a nearby field office." },
  { slug: "north-dakota", name: "North Dakota", abbr: "ND", dds: "North Dakota Disability Determination Services", note: "North Dakota DDS reviews medical evidence under federal law. SSDI is not a state general-assistance program." },
  { slug: "ohio", name: "Ohio", abbr: "OH", dds: "Ohio Division of Disability Determination", note: "Ohio DDD adjudicates SSDI medical eligibility. Hearing offices (OHO) in Ohio hear ALJ appeals after reconsideration." },
  { slug: "oklahoma", name: "Oklahoma", abbr: "OK", dds: "Oklahoma Disability Determination Division", note: "Oklahoma DDD applies federal SSDI rules. Oklahoma’s Consumer Data Protection Act is enacted with a 2027 effective date." },
  { slug: "oregon", name: "Oregon", abbr: "OR", dds: "Oregon Disability Determination Services", note: "Oregon DDS reviews claims under SSA listings. Oregon’s Consumer Privacy Act includes a right to know specific third-party recipients." },
  { slug: "pennsylvania", name: "Pennsylvania", abbr: "PA", dds: "Pennsylvania Bureau of Disability Determination", note: "Pennsylvania BDD reviews SSDI claims. Pennsylvania is an all-party consent state for call recording." },
  { slug: "rhode-island", name: "Rhode Island", abbr: "RI", dds: "Rhode Island Disability Determination Services", note: "Rhode Island DDS applies federal criteria. Rhode Island’s Data Transparency and Privacy Protection Act took effect in 2026." },
  { slug: "south-carolina", name: "South Carolina", abbr: "SC", dds: "South Carolina Disability Determination Services", note: "South Carolina DDS makes the medical decision for SSA. Keep treating with your SC providers — gaps in care are a common denial reason." },
  { slug: "south-dakota", name: "South Dakota", abbr: "SD", dds: "South Dakota Disability Determination Services", note: "South Dakota DDS uses SSA’s sequential evaluation. You can apply online from anywhere in the state at no charge." },
  { slug: "tennessee", name: "Tennessee", abbr: "TN", dds: "Tennessee Disability Determination Services", note: "Tennessee DDS reviews medical evidence. Tennessee’s Information Protection Act includes a revenue threshold and consumer rights." },
  { slug: "texas", name: "Texas", abbr: "TX", dds: "Texas Disability Determination Services", note: "Texas DDS is among the largest in the country. The Texas Data Privacy and Security Act applies to most for-profit businesses with no revenue floor." },
  { slug: "utah", name: "Utah", abbr: "UT", dds: "Utah Disability Determination Services", note: "Utah DDS applies federal listings. Utah’s Consumer Privacy Act covers qualifying businesses that collect Utah resident data." },
  { slug: "vermont", name: "Vermont", abbr: "VT", dds: "Vermont Disability Determination Services", note: "Vermont DDS reviews SSDI claims. Vermont’s Data Privacy and Online Surveillance Act is enacted with a 2028 effective date." },
  { slug: "virginia", name: "Virginia", abbr: "VA", dds: "Virginia Disability Determination Services", note: "Virginia DDS applies SSA rules. Virginia’s Consumer Data Protection Act was the model for many later state privacy laws." },
  { slug: "washington", name: "Washington", abbr: "WA", dds: "Washington Division of Disability Determination Services", note: "Washington DDDS reviews claims. Washington’s My Health My Data Act regulates consumer health data, and Washington is an all-party recording state." },
  { slug: "west-virginia", name: "West Virginia", abbr: "WV", dds: "West Virginia Disability Determination Section", note: "West Virginia DDS adjudicates SSDI medical eligibility. Black lung, musculoskeletal, and pulmonary claims still must meet SSA duration and SGA rules." },
  { slug: "wisconsin", name: "Wisconsin", abbr: "WI", dds: "Wisconsin Disability Determination Bureau", note: "Wisconsin DDB reviews claims under federal listings. File free at SSA.gov or a Wisconsin field office." },
  { slug: "wyoming", name: "Wyoming", abbr: "WY", dds: "Wyoming Disability Determination Services", note: "Wyoming DDS applies the same federal SSDI standard used in every other state. Sparse specialist access makes record gathering especially important." },
  { slug: "district-of-columbia", name: "District of Columbia", abbr: "DC", dds: "D.C. Disability Determination Division", note: "The District of Columbia DDS reviews claims for D.C. residents under SSA rules. D.C. has its own consumer-protection and data-security requirements." },
];

export function getState(slug: string) {
  return US_STATES.find((s) => s.slug === slug);
}
