/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AppealsRouteImport } from './routes/appeals'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as BlueBookRouteImport } from './routes/blue-book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DenialsRouteImport } from './routes/denials'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DoNotSellRouteImport } from './routes/do-not-sell'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HearingsRouteImport } from './routes/hearings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyRequestRouteImport } from './routes/privacy-request'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SmsTermsRouteImport } from './routes/sms-terms'
import { Route as SsdiVsSsiRouteImport } from './routes/ssdi-vs-ssi'
import { Route as StatesRouteImport } from './routes/states'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhatIsSsdiRouteImport } from './routes/what-is-ssdi'
import { Route as WorkCreditsRouteImport } from './routes/work-credits'
import { Route as SsdiStateRouteImport } from './routes/ssdi.$state'
import { Route as ApiVapiInboundRouteImport } from './routes/api.vapi.inbound'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealsRoute = AppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueBookRoute = BlueBookRouteImport.update({
  id: '/blue-book',
  path: '/blue-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DenialsRoute = DenialsRouteImport.update({
  id: '/denials',
  path: '/denials',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DoNotSellRoute = DoNotSellRouteImport.update({
  id: '/do-not-sell',
  path: '/do-not-sell',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HearingsRoute = HearingsRouteImport.update({
  id: '/hearings',
  path: '/hearings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRequestRoute = PrivacyRequestRouteImport.update({
  id: '/privacy-request',
  path: '/privacy-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsTermsRoute = SmsTermsRouteImport.update({
  id: '/sms-terms',
  path: '/sms-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SsdiVsSsiRoute = SsdiVsSsiRouteImport.update({
  id: '/ssdi-vs-ssi',
  path: '/ssdi-vs-ssi',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsSsdiRoute = WhatIsSsdiRouteImport.update({
  id: '/what-is-ssdi',
  path: '/what-is-ssdi',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkCreditsRoute = WorkCreditsRouteImport.update({
  id: '/work-credits',
  path: '/work-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const SsdiStateRoute = SsdiStateRouteImport.update({
  id: '/ssdi/$state',
  path: '/ssdi/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiInboundRoute = ApiVapiInboundRouteImport.update({
  id: '/api/vapi/inbound',
  path: '/api/vapi/inbound',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/appeals': typeof AppealsRoute
  '/application': typeof ApplicationRoute
  '/blue-book': typeof BlueBookRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/denials': typeof DenialsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/hearings': typeof HearingsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-request': typeof PrivacyRequestRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sms-terms': typeof SmsTermsRoute
  '/ssdi-vs-ssi': typeof SsdiVsSsiRoute
  '/states': typeof StatesRoute
  '/terms': typeof TermsRoute
  '/what-is-ssdi': typeof WhatIsSsdiRoute
  '/work-credits': typeof WorkCreditsRoute
  '/ssdi/$state': typeof SsdiStateRoute
  '/api/vapi/inbound': typeof ApiVapiInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/appeals': typeof AppealsRoute
  '/application': typeof ApplicationRoute
  '/blue-book': typeof BlueBookRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/denials': typeof DenialsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/hearings': typeof HearingsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-request': typeof PrivacyRequestRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sms-terms': typeof SmsTermsRoute
  '/ssdi-vs-ssi': typeof SsdiVsSsiRoute
  '/states': typeof StatesRoute
  '/terms': typeof TermsRoute
  '/what-is-ssdi': typeof WhatIsSsdiRoute
  '/work-credits': typeof WorkCreditsRoute
  '/ssdi/$state': typeof SsdiStateRoute
  '/api/vapi/inbound': typeof ApiVapiInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/appeals': typeof AppealsRoute
  '/application': typeof ApplicationRoute
  '/blue-book': typeof BlueBookRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/denials': typeof DenialsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/hearings': typeof HearingsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-request': typeof PrivacyRequestRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sms-terms': typeof SmsTermsRoute
  '/ssdi-vs-ssi': typeof SsdiVsSsiRoute
  '/states': typeof StatesRoute
  '/terms': typeof TermsRoute
  '/what-is-ssdi': typeof WhatIsSsdiRoute
  '/work-credits': typeof WorkCreditsRoute
  '/ssdi/$state': typeof SsdiStateRoute
  '/api/vapi/inbound': typeof ApiVapiInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/appeals'
    | '/application'
    | '/blue-book'
    | '/contact'
    | '/cookies'
    | '/denials'
    | '/disclaimer'
    | '/do-not-sell'
    | '/eligibility'
    | '/faq'
    | '/hearings'
    | '/privacy'
    | '/privacy-request'
    | '/resources'
    | '/services'
    | '/sms-terms'
    | '/ssdi-vs-ssi'
    | '/states'
    | '/terms'
    | '/what-is-ssdi'
    | '/work-credits'
    | '/ssdi/$state'
    | '/api/vapi/inbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/appeals'
    | '/application'
    | '/blue-book'
    | '/contact'
    | '/cookies'
    | '/denials'
    | '/disclaimer'
    | '/do-not-sell'
    | '/eligibility'
    | '/faq'
    | '/hearings'
    | '/privacy'
    | '/privacy-request'
    | '/resources'
    | '/services'
    | '/sms-terms'
    | '/ssdi-vs-ssi'
    | '/states'
    | '/terms'
    | '/what-is-ssdi'
    | '/work-credits'
    | '/ssdi/$state'
    | '/api/vapi/inbound'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/appeals'
    | '/application'
    | '/blue-book'
    | '/contact'
    | '/cookies'
    | '/denials'
    | '/disclaimer'
    | '/do-not-sell'
    | '/eligibility'
    | '/faq'
    | '/hearings'
    | '/privacy'
    | '/privacy-request'
    | '/resources'
    | '/services'
    | '/sms-terms'
    | '/ssdi-vs-ssi'
    | '/states'
    | '/terms'
    | '/what-is-ssdi'
    | '/work-credits'
    | '/ssdi/$state'
    | '/api/vapi/inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AppealsRoute: typeof AppealsRoute
  ApplicationRoute: typeof ApplicationRoute
  BlueBookRoute: typeof BlueBookRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DenialsRoute: typeof DenialsRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DoNotSellRoute: typeof DoNotSellRoute
  EligibilityRoute: typeof EligibilityRoute
  FaqRoute: typeof FaqRoute
  HearingsRoute: typeof HearingsRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyRequestRoute: typeof PrivacyRequestRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SmsTermsRoute: typeof SmsTermsRoute
  SsdiVsSsiRoute: typeof SsdiVsSsiRoute
  StatesRoute: typeof StatesRoute
  TermsRoute: typeof TermsRoute
  WhatIsSsdiRoute: typeof WhatIsSsdiRoute
  WorkCreditsRoute: typeof WorkCreditsRoute
  SsdiStateRoute: typeof SsdiStateRoute
  ApiVapiInboundRoute: typeof ApiVapiInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeals': {
      id: '/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blue-book': {
      id: '/blue-book'
      path: '/blue-book'
      fullPath: '/blue-book'
      preLoaderRoute: typeof BlueBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denials': {
      id: '/denials'
      path: '/denials'
      fullPath: '/denials'
      preLoaderRoute: typeof DenialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/do-not-sell': {
      id: '/do-not-sell'
      path: '/do-not-sell'
      fullPath: '/do-not-sell'
      preLoaderRoute: typeof DoNotSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearings': {
      id: '/hearings'
      path: '/hearings'
      fullPath: '/hearings'
      preLoaderRoute: typeof HearingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-request': {
      id: '/privacy-request'
      path: '/privacy-request'
      fullPath: '/privacy-request'
      preLoaderRoute: typeof PrivacyRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-terms': {
      id: '/sms-terms'
      path: '/sms-terms'
      fullPath: '/sms-terms'
      preLoaderRoute: typeof SmsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssdi-vs-ssi': {
      id: '/ssdi-vs-ssi'
      path: '/ssdi-vs-ssi'
      fullPath: '/ssdi-vs-ssi'
      preLoaderRoute: typeof SsdiVsSsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-ssdi': {
      id: '/what-is-ssdi'
      path: '/what-is-ssdi'
      fullPath: '/what-is-ssdi'
      preLoaderRoute: typeof WhatIsSsdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-credits': {
      id: '/work-credits'
      path: '/work-credits'
      fullPath: '/work-credits'
      preLoaderRoute: typeof WorkCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssdi/$state': {
      id: '/ssdi/$state'
      path: '/ssdi/$state'
      fullPath: '/ssdi/$state'
      preLoaderRoute: typeof SsdiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi/inbound': {
      id: '/api/vapi/inbound'
      path: '/api/vapi/inbound'
      fullPath: '/api/vapi/inbound'
      preLoaderRoute: typeof ApiVapiInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AppealsRoute: AppealsRoute,
  ApplicationRoute: ApplicationRoute,
  BlueBookRoute: BlueBookRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DenialsRoute: DenialsRoute,
  DisclaimerRoute: DisclaimerRoute,
  DoNotSellRoute: DoNotSellRoute,
  EligibilityRoute: EligibilityRoute,
  FaqRoute: FaqRoute,
  HearingsRoute: HearingsRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyRequestRoute: PrivacyRequestRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SmsTermsRoute: SmsTermsRoute,
  SsdiVsSsiRoute: SsdiVsSsiRoute,
  StatesRoute: StatesRoute,
  TermsRoute: TermsRoute,
  WhatIsSsdiRoute: WhatIsSsdiRoute,
  WorkCreditsRoute: WorkCreditsRoute,
  SsdiStateRoute: SsdiStateRoute,
  ApiVapiInboundRoute: ApiVapiInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
